// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using School_System_APII.Connection;

#nullable disable

namespace School_System_APII.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("School_System_APII.Models.Instractor", b =>
                {
                    b.Property<int>("InstractorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstractorId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstractorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("InstractorId");

                    b.HasIndex("SubjectId")
                        .IsUnique()
                        .HasFilter("[SubjectId] IS NOT NULL");

                    b.ToTable("instractors");

                    b.HasData(
                        new
                        {
                            InstractorId = 1,
                            Email = "Saber@gmail.com",
                            InstractorName = "Saber",
                            Password = "Saber@123",
                            Salary = 1000,
                            SubjectId = 1
                        });
                });

            modelBuilder.Entity("School_System_APII.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InstractorId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("StudentId");

                    b.HasIndex("InstractorId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Email = "Magdy@gmail.com",
                            FullName = "Magdy Emad",
                            InstractorId = 1,
                            Password = "Magdy@123",
                            SubjectId = 1,
                            UserName = "Magdy7"
                        });
                });

            modelBuilder.Entity("School_System_APII.Models.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectId"));

                    b.Property<int?>("InstractorId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("SubjectId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            SubjectId = 1,
                            InstractorId = 1,
                            Password = "Arabic@123",
                            SubjectName = "Arabic"
                        });
                });

            modelBuilder.Entity("School_System_APII.Models.Instractor", b =>
                {
                    b.HasOne("School_System_APII.Models.Subject", "Subject")
                        .WithOne("Instractor")
                        .HasForeignKey("School_System_APII.Models.Instractor", "SubjectId");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("School_System_APII.Models.Student", b =>
                {
                    b.HasOne("School_System_APII.Models.Instractor", "Instractor")
                        .WithMany("Students")
                        .HasForeignKey("InstractorId");

                    b.HasOne("School_System_APII.Models.Subject", "Subject")
                        .WithMany("Students")
                        .HasForeignKey("SubjectId");

                    b.Navigation("Instractor");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("School_System_APII.Models.Instractor", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("School_System_APII.Models.Subject", b =>
                {
                    b.Navigation("Instractor")
                        .IsRequired();

                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
